### ISSUE TITLE
node >=16

### ISSUE THREAD

**Issue by bobenkovadym** [Adslot/node-migrations#44]
make this compatible with node 17 please

**Comment by bchew** [comment]
@bobenkovadym we have published `v1.2.1-beta` as a prerelease version on npm so you would be able to install it via `migrations@1.2.1-beta` which is based off the `next` branch: https://github.com/Adslot/node-migrations/tree/next

Our policy is to standardise the nodejs version in use to the current LTS across our projects so it can be adequately tested so this change would not be applied to `@latest` until node 18 becomes LTS.
